spring.application.name=iopet

# Supabase configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Pool de conexões
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000

# Não criar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Endpoint para verificar a conexão
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always